#!/bin/sh
# postrm script for canaima-plymouth
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Segun sea la marca de la tarjeta de video, se deben cargar diferentes modulos
        # mediante el archivo /etc/initramfs-tools/modules.
        if lspci | grep VGA | grep -i '\<nvidia\>'
        then
		sed -i 's/^drm$//g' /etc/initramfs-tools/modules
		sed -i 's/^nouveau modeset=1$//g' /etc/initramfs-tools/modules
        fi

        if lspci | grep VGA | grep -i '\<intel\>'
        then
		sed -i 's/^intel_agp$//g' /etc/initramfs-tools/modules
		sed -i 's/^drm$//g' /etc/initramfs-tools/modules
		sed -i 's/^i915 modeset=1$//g' /etc/initramfs-tools/modules
        fi
        
        if lspci | grep VGA | grep -i '\<ati\>'
        then
		sed -i 's/^uvesafb mode_option=800x600 mtrr=3 scroll=ywrap$//g' /etc/initramfs-tools/modules
		sed -i 's/^FRAMEBUFFER=y$//g' /etc/initramfs-tools/conf.d/splash
        fi

        # Se establece como tema a fade-in
        grep -q '^[[]Daemon[]]' ${PLYMOUTH_CONFDIR}/plymouthd.conf 2> /null || echo '[Daemon]' >> ${PLYMOUTH_CONFDIR}/plymouthd.conf
        sed -i -e '/^Theme[[:blank:]]*=.*/d' ${PLYMOUTH_CONFDIR}/plymouthd.conf
        sed -i -e "s/^\([[]Daemon[]]\)\n*/\1\nTheme=fade-in/" ${PLYMOUTH_CONFDIR}/plymouthd.conf

	if [ -x $( which plymouth-set-default-theme ) ]; then
		plymouth-set-default-theme canaima-plymouth || true
	fi

        # Se actualiza el archivo de inicializacion que se ejecuta al iniciar el equipo.
	if [ -x $( which update-initramfs ) ]; then
		update-initramfs -u
	fi

	if [ -x $( which update-burg ) ]; then
		sync
		update-burg || true
	fi

	if [ -x $( which update-grub ) ]; then
		sync
		update-grub || true
	fi

    ;;

    *)
        echo "postrm con argumento desconocido \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
