#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-plymouth
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

PLYMOUTHCONF="/etc/plymouth/plymouthd.conf"
INITRAMFSMOD="/etc/initramfs-tools/modules"
INITRAMFSPLASH="/etc/initramfs-tools/conf.d/splash"

case ${1} in
    configure)

	if [ -e /etc/init.d/plymouth ]; then
		sed -i 's/TEXT="Shutting down system..."/TEXT="Apagando el equipo... Recuerda: ¡Ahorrar energía es salvar al planeta!"/g' /etc/init.d/plymouth
		sed -i 's/TEXT="Restarting system..."/TEXT="Reiniciando el equipo..."/g' /etc/init.d/plymouth
	fi

	# Segun sea la marca de la tarjeta de video, se deben cargar diferentes modulos 
	# mediante el archivo /etc/initramfs-tools/modules.
	if [ $( lspci | grep "VGA" | grep -iwc "nvidia" ) == 1 ]; then
		ADVERTENCIA "Configurando Canaima Plymouth para tarjeta NVIDIA ..."
		if [ $( cat ${INITRAMFSMOD} | grep -iwc "^drm$" ) == 0 ] \
		&& [ $( cat ${INITRAMFSMOD} | grep -iwc "^nouveau modeset=1$" ) == 0 ]; then
			echo "drm" >> ${INITRAMFSMOD}
			echo "nouveau modeset=1" >> ${INITRAMFSMOD}
		fi
	fi

	if [ $( lspci | grep "VGA" | grep -iwc "intel" ) == 1 ]; then
		ADVERTENCIA "Configurando Canaima Plymouth para tarjeta INTEL ..."
		if [ $( cat ${INITRAMFSMOD} | grep -iwc "^intel_agp$" ) == 0 ] \
		&& [ $( cat ${INITRAMFSMOD} | grep -iwc "^drm$" ) == 0 ] \
		&& [ $( cat ${INITRAMFSMOD} | grep -iwc "^i915 modeset=1$" ) == 0 ]; then
			echo "intel_agp" >> ${INITRAMFSMOD}
			echo "drm" >> ${INITRAMFSMOD}
			echo "i915 modeset=1" >> ${INITRAMFSMOD}
		fi
	fi

	if [ $( lspci | grep "VGA" | grep -iwc "ati" ) == 1 ]; then 
		ADVERTENCIA "Configurando Canaima Plymouth para tarjeta ATI ..."
		if [ $( cat ${INITRAMFSMOD} | grep -iwc "^uvesafb mode_option=800x600 mtrr=3 scroll=ywrap$" ) == 0 ] \
		&& [ $( cat ${INITRAMFSPLASH} | grep -iwc "^FRAMEBUFFER=y$" ) == 0 ]; then
			echo "uvesafb mode_option=800x600 mtrr=3 scroll=ywrap" >> ${INITRAMFSMOD}
			echo "FRAMEBUFFER=y" >> ${INITRAMFSPLASH}
		fi
	fi

	# Se establece como tema a canaima-plymouth.
	if [ $( grep -wc "^[[]Daemon[]]$" ${PLYMOUTHCONF} ) == 0 ]; then
		echo "[Daemon]" >> ${PLYMOUTHCONF}
	fi

	sed -i -e '/^Theme[[:blank:]]*=.*/d' ${PLYMOUTHCONF}
	sed -i -e "s/^\([[]Daemon[]]\)\n*/\1\nTheme=canaima-plymouth/" ${PLYMOUTHCONF}

	if [ -n $( which plymouth-set-default-theme ) ] && [ -x $( which plymouth-set-default-theme ) ]; then
		plymouth-set-default-theme canaima-plymouth || true
	fi

	# Se actualiza el archivo de inicializacion que se ejecuta al iniciar el equipo.
	if [ -n $( which update-initramfs ) ] && [ -x $( which update-initramfs ) ]; then
		update-initramfs -u
	fi

	if [ -n $( which update-burg ) ] && [ -x $( which update-burg ) ]; then
		sync
		update-burg || true
	fi

	if [ -n $( which update-grub ) ] && [ -x $( which update-grub ) ]; then
		sync
		update-grub || true
	fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "Falto un argumento en el postinst \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
