#!/bin/sh
# postinst script for canaima-plymouth
#
# see: dh_installdeb(1)

PLYMOUTH_CONFDIR="/etc/plymouth"
set -e

case "$1" in
    configure)

	if [ -e /etc/init.d/plymouth ]; then
	sed -i 's/TEXT="Shutting down system..."/TEXT="Apagando el equipo... Recuerda: ¡Ahorrar energía es salvar al planeta!"/g' /etc/init.d/plymouth
	sed -i 's/TEXT="Restarting system..."/TEXT="Reiniciando el equipo..."/g' /etc/init.d/plymouth
	fi

	# Segun sea la marca de la tarjeta de video, se deben cargar diferentes modulos 
	# mediante el archivo /etc/initramfs-tools/modules.
	if lspci | grep VGA | grep -i '\<nvidia\>' 1>/dev/null
	then 
		echo "drm" >> /etc/initramfs-tools/modules
		echo "nouveau modeset=1" >> /etc/initramfs-tools/modules
	fi
	if lspci | grep VGA | grep -i '\<intel\>' 1>/dev/null
	then 
                echo "intel_agp" >> /etc/initramfs-tools/modules
                echo "drm" >> /etc/initramfs-tools/modules
                echo "i915 modeset=1" >> /etc/initramfs-tools/modules
	fi
	if lspci | grep VGA | grep -i '\<ati\>' 1>/dev/null
	then 
		echo "uvesafb mode_option=800x600 mtrr=3 scroll=ywrap" >> /etc/initramfs-tools/modules
		echo FRAMEBUFFER=y | tee /etc/initramfs-tools/conf.d/splash 
	fi

	# Se establece como tema a canaima-plymouth.
	grep -q '^[[]Daemon[]]' ${PLYMOUTH_CONFDIR}/plymouthd.conf 2> /null || echo '[Daemon]' >> ${PLYMOUTH_CONFDIR}/plymouthd.conf
	sed -i -e '/^Theme[[:blank:]]*=.*/d' ${PLYMOUTH_CONFDIR}/plymouthd.conf
	sed -i -e "s/^\([[]Daemon[]]\)\n*/\1\nTheme=canaima-plymouth/" ${PLYMOUTH_CONFDIR}/plymouthd.conf

	if [ -x $( which plymouth-set-default-theme ) ]; then
		plymouth-set-default-theme canaima-plymouth || true
	fi

	# Se actualiza el archivo de inicializacion que se ejecuta al iniciar el equipo.
	if [ -x $( which update-initramfs ) ]; then
		update-initramfs -u
	fi

	if [ -x $( which update-burg ) ]; then
		sync
		update-burg || true
	fi

	if [ -x $( which update-grub ) ]; then
		sync
		update-grub || true
	fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "Falto un argumento en el postinst \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
